// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_you_have_reached_25000_m_speed_increased = "CgkI2YLQ_YUNEAIQFQ"; // <GPGSID>
        public const string achievement_life_gained_for_4000_coins = "CgkI2YLQ_YUNEAIQJA"; // <GPGSID>
        public const string achievement_you_have_reached_40000_m_speed_increased = "CgkI2YLQ_YUNEAIQGQ"; // <GPGSID>
        public const string achievement_you_have_reached_37500_m_speed_increased = "CgkI2YLQ_YUNEAIQHw"; // <GPGSID>
        public const string leaderboard_collected_coins = "CgkI2YLQ_YUNEAIQAw"; // <GPGSID>
        public const string achievement_you_have_reached_22500_m_speed_increased = "CgkI2YLQ_YUNEAIQFA"; // <GPGSID>
        public const string achievement_life_gained_for_6000_coins = "CgkI2YLQ_YUNEAIQJQ"; // <GPGSID>
        public const string achievement_you_have_collected_15000_coins = "CgkI2YLQ_YUNEAIQEA"; // <GPGSID>
        public const string leaderboard_total_collected_coins = "CgkI2YLQ_YUNEAIQHQ"; // <GPGSID>
        public const string achievement_you_have_reached_20000_m_speed_increased = "CgkI2YLQ_YUNEAIQEw"; // <GPGSID>
        public const string achievement_you_have_collected_10000_coins = "CgkI2YLQ_YUNEAIQDQ"; // <GPGSID>
        public const string achievement_you_have_reached_17500_m_speed_increased = "CgkI2YLQ_YUNEAIQEg"; // <GPGSID>
        public const string achievement_you_have_collected_5000_coins = "CgkI2YLQ_YUNEAIQCw"; // <GPGSID>
        public const string achievement_you_have_reached_35000_m_speed_increased = "CgkI2YLQ_YUNEAIQGA"; // <GPGSID>
        public const string achievement_you_have_collected_20000_coins = "CgkI2YLQ_YUNEAIQEQ"; // <GPGSID>
        public const string achievement_you_have_collected_12500_coins = "CgkI2YLQ_YUNEAIQDw"; // <GPGSID>
        public const string achievement_you_have_collected_7500_coins = "CgkI2YLQ_YUNEAIQDA"; // <GPGSID>
        public const string achievement_you_have_reached_47500_m_speed_increased = "CgkI2YLQ_YUNEAIQIg"; // <GPGSID>
        public const string achievement_you_have_reached_7500_m_speed_increased = "CgkI2YLQ_YUNEAIQBg"; // <GPGSID>
        public const string achievement_you_have_collected_2500_coins = "CgkI2YLQ_YUNEAIQDg"; // <GPGSID>
        public const string achievement_you_have_collected_500_coins = "CgkI2YLQ_YUNEAIQCg"; // <GPGSID>
        public const string achievement_god_mode_activated = "CgkI2YLQ_YUNEAIQGw"; // <GPGSID>
        public const string achievement_you_have_reached_32500_m_speed_increased = "CgkI2YLQ_YUNEAIQHg"; // <GPGSID>
        public const string achievement_you_have_reached_15000_m_speed_increased = "CgkI2YLQ_YUNEAIQCQ"; // <GPGSID>
        public const string achievement_you_have_reached_5000_m_speed_increased = "CgkI2YLQ_YUNEAIQBQ"; // <GPGSID>
        public const string achievement_you_have_reached_30000_m_speed_increased = "CgkI2YLQ_YUNEAIQFw"; // <GPGSID>
        public const string leaderboard_best_distance = "CgkI2YLQ_YUNEAIQAg"; // <GPGSID>
        public const string achievement_you_have_reached_27500_m_speed_increased = "CgkI2YLQ_YUNEAIQFg"; // <GPGSID>
        public const string achievement_you_have_reached_12500_m_speed_increased = "CgkI2YLQ_YUNEAIQCA"; // <GPGSID>
        public const string achievement_life_gained_for_8000_coins = "CgkI2YLQ_YUNEAIQJg"; // <GPGSID>
        public const string achievement_life_gained_for_2000_coins = "CgkI2YLQ_YUNEAIQIw"; // <GPGSID>
        public const string achievement_you_have_reached_45000_m_speed_increased = "CgkI2YLQ_YUNEAIQGg"; // <GPGSID>
        public const string achievement_you_have_reached_2500_m_speed_increased = "CgkI2YLQ_YUNEAIQBA"; // <GPGSID>
        public const string achievement_you_have_reached_10000_m_speed_increased = "CgkI2YLQ_YUNEAIQBw"; // <GPGSID>
        public const string achievement_life_gained_for_10000_coins = "CgkI2YLQ_YUNEAIQJw"; // <GPGSID>
        public const string achievement_you_have_reached_42500_m_speed_increased = "CgkI2YLQ_YUNEAIQIQ"; // <GPGSID>
        public const string achievement_you_have_reached_500_m_speed_increased = "CgkI2YLQ_YUNEAIQHA"; // <GPGSID>

}

